---
defaultStorageClass: basic
storageProviders:
  - storageClass: basic
    managementProvider: NFS
    pvNamePrefix: basic-
    configuration:
      identity:
        privateKeyFile:
        privateKey:
      provider: zfs
      ssh:
        hostname: ssh-pv-basic.default.svc.cluster.local
        port: 22
        identity: pvmanager
        privateKeyFile: .ssh/id_rsa
        token:
      nfs:
        hostname: nfs-pv-basic.default.svc.cluster.local
        exportRoot: /exports/openshift/persistentvolumes/basic
      zfs:
        rootPath: zpool/persistentvolumes/basic
        becomeRoot: true
  - storageClass: ssd
    managementProvider: NFS
    pvNamePrefix: ssd-
    configuration:
      provider: zfs
      ssh:
        hostname: ssh-pv-ssd.default.svc.cluster.local
        port: 22
        identity: pvmanager
        privateKeyFile: .ssh/id_rsa
        token:
      nfs:
        hostname: nfs-pv-ssd.default.svc.cluster.local
        exportRoot: /exports/openshift/persistentvolumes/ssd
      zfs:
        rootPath: zpool/persistentvolumes/ssd
        becomeRoot: true
