---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: examples.crds.kubernetes.wimsey.us

  # We configure a finalizer so we get notified when the object
  # is deleted so we can cleanup our resources before it disappears from k8s
  finalizers:
    - finalizer.example.crds.kubernetes.wimsey.us
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: crds.kubernetes.wimsey.us
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: examples
    # singular name to be used as an alias on the CLI and for display
    singular: example
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ExampleCRD
    # shortNames allow shorter string to match your resource on the CLI
#    shortNames:
#      - example
