---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-operator-{{ ocp_application_name }}
#oadm policy add-cluster-role-to-user view system:serviceaccount:ops:crd-operator-{{ ocp_application_name }}
