---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pvmanager.wimsey.us/clone-from: "example-pvc"
  name: example-cloned-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
