---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: basic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    kubernetes.io/description: Standard RAID10 storage
    wimsey.us/pvmanager-storageclass: "basic"
provisioner: wimsey.us/pvmanager
parameters:
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  annotations:
    kubernetes.io/description: SSD RAID10 storage
    wimsey.us/pvmanager-storageclass: "ssd"
provisioner: wimsey.us/pvmanager
parameters:
